### ISSUE TITLE
Swagger UI doesnt come up

### ISSUE THREAD

**Issue by jetheurer** [fliptoo/swagger-express#31]
Running http://localhost:3000/, I only see:
<img width="280" alt="screen shot 2015-09-15 at 1 29 12 pm" src="https://cloud.githubusercontent.com/assets/3021223/9884551/4e8b1728-5bae-11e5-9cb0-aa01138bb900.png">
Where is the Swagger UI?

**Comment by fliptoo** [comment]
Please run http://localhost:3000/swagger

**Comment by esperancaJS** [comment]
The recommended solution only shows JSON
